---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: myweb
 spec:
   replicas: 2
   template:
     metadata:
       labels:
         app: myweb
     spec:
       containers:
         - name: front-end
           image: nginx
           ports:
             - containerPort: 80
         - name: myweb
           image: 192.168.58.135:8083/myweb:1.0.0
           ports:
             - containerPort: 88
